### ISSUE TITLE
ATS

### ISSUE THREAD

**Issue by LegitSoulja** [RayRay5/ets2_savegame_editor#2]
Thanks for the source. I will follow the styles and make one for ATS.

**Comment by RayRay5** [comment]
This one is already wortking for ATS, it's just called different ;)

**Comment by Bluscream** [comment]
> 
> 
> Thanks for the source. I will follow the styles and make one for ATS.

gay

**Comment by LegitSoulja** [comment]
@Bluscream same as you?

**Comment by Bluscream** [comment]
:'D
---
Sent from my Lenovo TAB 2 A10-70L running Android 6.0 via OctoDroid v4.3.2
