### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException: 'The given key was not present in the dictionary.'

### ISSUE THREAD

**Issue by Bluscream** [RayRay5/ets2_savegame_editor#8]
![devenv_2018-10-15_20-55-57](https://user-images.githubusercontent.com/3318223/46971608-fd275b00-d0ab-11e8-90db-50ea6563d064.png)

**Comment by RayRay5** [comment]
Sorry for the late reply, but in this case your language fiel has too few lines.
Please add more translated lines to the language file or use the english version which you can find in the zip file that contains all the other files (lang and config files)

**Comment by RayRay5** [comment]
Alternatively, check if your project folder has the /lang folder present as well

**Comment by RayRay5** [comment]
It definitely has something to do with the missing lang(uage) folder.
The folder needs to be existant, also in the project debug/release folder

C:\Users\RayRay5\source\repos\ets2_saveedit\WindowsFormsApplication1\bin\x64\Debug\lang <-- needs to exist
C:\Users\RayRay5\source\repos\ets2_saveedit\WindowsFormsApplication1\bin\x64\Debug\lang\lang_en.txt <-- if you use english (by default) language, you need this file as well

You can find the files in the executables folder. Just copy them to the Debug/Release Folder
ETS2_SaveEditor_v1.1_final_win_x64_fullpackage.zip\release_1.1_final\lang
You can find the fullpackage.zip in this github directory ets2_savegame_editor/SaveEditor Version 1.x/executables/release_1.1_final/

**Comment by Bluscream** [comment]
Sorry i don't play ETS2 anymore
